---
- name: Create pods using deployment 
  hosts: kuber 
  
  user: root
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f appdeploy.yml
 
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment app-deployment
