apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: kube-ansible
spec:
  type: NodePort
  selector:
   app: kube-ansible
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
